# Generated by Django 4.0.3 on 2022-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_url',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
