# Generated by Django 4.0.3 on 2022-04-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='meal_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
