# Generated by Django 4.0.3 on 2022-04-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_content_comment_meal_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Menu',
        ),
    ]
