# Generated by Django 4.0.3 on 2022-04-14 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_post_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='photo_url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
